version: '2'

services:
  web:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../src:/var/www/html
    links:
      - db
    environment:
      DBNAME: liquidapp
      DBUSER: liquiduser
      DBPASS: liquiduser
      DBHOST: db
    command: ["test"]
  db: 
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: liquiduser
      MYSQL_PASSWORD: liquiduser
      MYSQL_DATABASE: liquidapp

  agent:
    image: ansible-agent
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
