version: '2'

volumes:
  datavol:
    driver: local

services:
  web:
    build: 
      context: ../../
      dockerfile: docker/release/Dockerfile
    volumes:
      - datavol:/var/www/html
    links:
      - db
    environment:
      DBNAME: liquidapp
      DBUSER: liquiduser
      DBPASS: liquiduser
      DBHOST: db
  db: 
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: liquiduser
      MYSQL_PASSWORD: liquiduser
      MYSQL_DATABASE: liquidapp
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  agent-db:
    image: ansible-agent
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

  agent-lb:
    image: ansible-agent
    links:
      - lb
    environment:
      PROBE_HOST: "lb"
      PROBE_PORT: "80"

  test:
    image: reltester
    links:
      - lb
